### ISSUE TITLE
Logger issue

### ISSUE THREAD

**Issue by lielran** [jswift/aws-kotlin-jvm-gradle#1]
while running the function on lambda:
Error loading class com.xxx.Handler: org/apache/logging/log4j/LogManager: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
at com.xxx.Handler.<clinit>(Handler.kt:20)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 3 more

**Comment by jswift** [comment]
I'm unable to replicate that running
```
serverless create --template-url https://github.com/jswift/aws-kotlin-jvm-gradle --path helloworld --name hello && cd helloworld
gradle deploy
serverless invoke -f hello
```


What does your handler class look like? What steps did you follow to get the error?

**Comment by lielran** [comment]
I'm not sure how I did it but now it's working. I think I deploy the wrong jar when it happens
